name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like reel to do?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why?
      description: What are you trying to make or record?
